### ISSUE TITLE
DSV data provider

### ISSUE THREAD

**Issue by dcardosods** [google/kratu#2]
What about a DSV data provider?

**Comment by tarjeiv** [comment]
Hi dcardosods!
How about adding the possibility to have a custom field and record delimiters in the CSV Data Provider?
- Tarjei

**Comment by dcardosods** [comment]
I think it is a good option.
But i proposed create a new Data Provider because in CSV "specification" the delimiter is always a comma. A DSV file is a variation where often, the decimal separator is a comma and the value separator is a semicolon.
If adding a custom field for a delimiter in the CSV Data Provider, i think that not will be only a CSV Data Provider.

**Comment by tarjeiv** [comment]
OK, we'll see if we can include a generic field/row separator in a future release.
If you need it before, your welcome to fork, implement and submit a pull request.
